services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=salman
    
    # env_file:
    #   - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
    volumes:
    - ./data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
  
networks:
  postgres-network:
    