services:
  postgres:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salman
    
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redisdata:/data

volumes:
  pgdata:
  redisdata: 
